{% set name = "pytest-postgresql" %}
{% set version = "5.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-postgresql-{{ version }}.tar.gz
  sha256: edc1e83f65e9276bf465a983bfee98799866ee067defcee586ef6f889218e91f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - pytest >=6.2
    - port-for >=0.6.0
    - mirakuru
    - setuptools
    - psycopg >=3.0.0

test:
  imports:
    - pytest_postgresql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ClearcodeHQ/pytest-postgresql
  summary: Postgresql fixtures and fixture factories for Pytest.
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.lesser

extra:
  recipe-maintainers:
    - asford
