{% set name = "pytest-postgresql" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7127d4f875d92db99bd3a99303b4e6eff8af2937a5c45133245b4a3b5919c6f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - pytest >=6.2
    - port-for >=0.6.0
    - mirakuru
    - setuptools
    - psycopg >=3.0.0

test:
  imports:
    - pytest_postgresql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ClearcodeHQ/pytest-postgresql
  summary: Postgresql fixtures and fixture factories for Pytest.
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.lesser

extra:
  recipe-maintainers:
    - asford
