{% set name = "pytest-postgresql" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-postgresql-{{ version }}.tar.gz
  sha256: 22edcbafab8995ee85b8d948ddfaad4f70c2c7462303d7477ecd2f77fc9d15bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - mirakuru >=2.3.0
    - port-for
    - pytest >=6.2.0
    - python >=3.7
    - setuptools

test:
  imports:
    - pytest_postgresql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ClearcodeHQ/pytest-postgresql
  summary: Postgresql fixtures and fixture factories for Pytest.
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.lesser

extra:
  recipe-maintainers:
    - asford
